name: Update Medium Stories

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
  
        - name: Fetch Medium RSS
          run: |
            python .github/workflows/update_medium.py
  
        - name: Commit changes
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add README.md
            git diff --staged --quiet || git commit -m "Update Medium stories"
            git push
